# returned from popup to be placed in storage
type videoData
{
    title: string,
    channel: string,
    url: string,
    videoId: string,

    duration: float,
    currentTime: float,

    saveDate: datestring,

    done?: bool
}

type localStorage
{
    [videoData.videoId]: videoData
}